apiVersion: v1
kind: Secret
metadata:
  name: objectstorage-provisioner
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-ceph
    app.kubernetes.io/version: main
    app.kubernetes.io/name: cosi-driver-ceph
type: Opaque
stringData:
  ENDPOINT: "http://rook-ceph-rgw-my-store.rook-ceph.svc.cluster.local:80"
  ACCESSKEY: "LKHN8KQCP2K0ULN0QWGF"
  SECRETKEY: "CIByqLRD3OikLZHhACLB6hHiQ9MgvLg1yiy4K5CT"
